### ISSUE TITLE
AST: changing coordinate system results in incorrect tick labels

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#52]
using IDIA carta with frontend version: b9e44e2

To reproduce:
1) open orion_12co_hera.hdf5
2) we should see correct cursor coordinate and tick label coordinate
![screen shot 2018-10-19 at 9 14 14 am](https://user-images.githubusercontent.com/20819712/47192651-03a22500-d381-11e8-9410-f20c89d383d6.png)

3) now change the coordinate system from FK5 to galactic
4) issue 1: the tick label format should be changed to degree automatically.
![screen shot 2018-10-19 at 9 15 31 am](https://user-images.githubusercontent.com/20819712/47192684-2df3e280-d381-11e8-974a-2489730d5f93.png)

5) issue 2: by manually changing the format to degree, the tick labels (incorrect) are not consistent with the cursor coordinate which should be the correct one. 
![screen shot 2018-10-19 at 9 15 56 am](https://user-images.githubusercontent.com/20819712/47192712-554aaf80-d381-11e8-8d39-a3e039a7432f.png)

6) similarly, with supermosaic.10.hdf5, changing from galactic to FK5 results in the same issue.

**Comment by veggiesaurus** [comment]
@kswang1029 Can you clarify which tick format should be used for each of the coordinate systems? It seems AST's defaults are slightly different to those that you requested. The systems are:

- FK4
- FK5
- Galactic
- Ecliptic
- ICRS

**Comment by kswang1029** [comment]
FK4: hms/dms
FK5: hms/dms
Galactic: degree/degree
Ecliptic: degree/degree
ICRS: hms/dms

**Comment by confluence** [comment]
This has been fixed in my branch. (Cursor format changes are not immediately visible, but become visible as soon as the cursor moves.)

**Comment by veggiesaurus** [comment]
@ad

**Comment by veggiesaurus** [comment]
fixed in #59

**Comment by kswang1029** [comment]
with frontend version: b17a8aa, is the issue 2 supposed to be fixed? It appears the issue is still there. The tick labels and cursor WCS are not consistent. 
<img width="816" alt="screen shot 2018-10-24 at 09 28 04" src="https://user-images.githubusercontent.com/20819712/47400353-66276680-d76f-11e8-8236-70c710d34ad4.png">

**Comment by veggiesaurus** [comment]
@confluence can you look into this? I'm opening the issue again

**Comment by kswang1029** [comment]
@confluence #53 is about the cursor value crossing 0h and 12h line. The issue 2 here is after coordinate transformation, the cursor values are still correct, but not the tick labels.

**Comment by veggiesaurus** [comment]
> with frontend version: b17a8aa, is the issue 2 supposed to be fixed? It appears that the issue is still there. The tick labels and cursor WCS are not consistent after switching to non-native coordinate. The example below is galactic --> FK5

Yes, it looks like AST isn't applying the normalisation to the tick labels consistently.

**Comment by kswang1029** [comment]
@confluence Upate: tick labels are correct. Cursor values are not correct. Sorry for confusion.

**Comment by confluence** [comment]
As far as I can see, the issue here is that the cursor values are not using the transformed *coordinates* -- when the system is changed, the cursor continues to use the native system.

**Comment by confluence** [comment]
Yes, that was it. I'm going to commit a fix.

**Comment by veggiesaurus** [comment]
@kswang1029 merged into master and updated dev-viewer for verification before closing

**Comment by kswang1029** [comment]
@confluence Thanks for fixing this. @veggiesaurus Yes, verified.
